on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Deploy Jigsaw using GoStatic
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer PHP dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install NPM dependencies
        run: npm install

      - name: Build the site
        run: npm run prod

      - name: Deploy
        id: deploy
        uses: DigitalSVN/GoStatic@v1.0
        with:
          api-token: ${{ secrets.DICASHI_API_TOKEN }}
          source-dir: "./build_production"

      - name: Output the deployment URL
        run: echo "URL ${{ steps.deploy.outputs.url }}"

      - name: Output the deployment URL in a comment on the pull request
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'URL ready:  ${{ steps.deploy.outputs.url }}' });